### ISSUE TITLE
BUG : pas de BGM et BGS natif avec la commande start_new_game

### ISSUE THREAD

**Issue by Spyrojojo** [funkywork/RME#57]
Quand la commande start_new_game est utilisé, les BGM et les BGS natif de la map ou nous somme envoyer ne sont pas jouer (cependant par la suite nous pouvons jouer un BGM et un BGS avec la commande en event de RM)

**Comment by Grimimi** [comment]
Fixed ! 
Merci :) (et bravo pour tes contributions récentes)
