### ISSUE TITLE
Problème déclenchements personnalisés avec SV

### ISSUE THREAD

**Issue by Feezen** [funkywork/RME#66]
J'ai un problème, je ne sais pas si c'est un bug ou si je n'ai pas bien compris l'utilisation des variables locales, mais en gros quand je met la valeur d'une variable SV[1] à 3, par exemple, sur un évènement, elle est aussi mise à 3 dans un second sur la même map.

(Pour tester d'où venait mon problème, j'ai mis dans le premier event SV[1] = 3 et dans le second j'ai rajouté une page avec tout en haut "trigger{SV[1] == 3}", et dès que je parle au premier les actions qui suivent trigger sont activées. J'ai aussi essayé en précisant SV[1, @event_id, 1] mais j'ai le même problème.)

Sinon super boulot ;)

**Comment by Ibiky** [comment]
Salut ces normal, tu ne peut pas utiliser directement le SV sur le même événement, ce qui veut dire que si du a 2 évent, 1 et 2, tu utilise SV[1] dans l'évent 1 et que tu veux l'utiliser dans l'évent 2 tu dois faire SV[1, 1] dans le 2eme évent.

Pour utiliser @event_id (ou me) par exemple dans l'évent 1 tu fait SV[@event_id] il sera = à 1 et si tu le copy il sera = à 2, inssis de suite, du coups pour utiliser le SV dans un autre évent ces pareil que tout a l'heure tu dois faire SV[1, 1] ou SV[2, 1] par contre ci ces une autre maps ces la que tu utiliser les 3 commandes.

**Comment by Feezen** [comment]
Je ne me suis pas bien expliqué ^^ En faite mon problème c'est que mes variables locales marchent étrangement comme des variables globales.

(Si je fais le même test avec l'EE4 par exemple, ça fonctionne bien, alors qu'ici si je modifie une variable locale d'un évent, elle se retrouve modifiée dans tout les autres!)

**Comment by Feezen** [comment]
Alors, une idée pour ce problème? :(

**Comment by xvw** [comment]
`SV[1, @event_id, 1] `
Déjà ici, l'ordre semble mauvais.

**Comment by Feezen** [comment]
Pourtant dans la doc l'usage est "SV[id_de_la_map, id_de_levenement, id]" (donc la je midifiais sur la map 1, dans l'event appelé sa variable locale n°1, non?)

Mais même en utilisant SV[1] le problème persiste, et c'est uniquement dans les trigger.
Si j'active SV[1] dans n'importe quel event, le trigger se déclenche. 
J'enverrais des screen des que j'aurais accès à mon ordinateur.

**Comment by xvw** [comment]
Il faudra que je teste :v désolé (j'avais mal lu). 
Tu es sur que dans les triggers tu as bien des double égals ? Pas d'égals simple?

**Comment by Jauke** [comment]
Bonjour Feezen.

Tu es bien sûr d'avoir la dernière version de RME ?

Une fois, on a effectivement corrigé un problème sur les variables et interrupteurs locaux.
Mais tout est suppisé être ok depuis, puisqu'il y a déjà des projets qui font une utilisation complexe des variables locales sans rencontrer de problème, apparemment.

**Comment by Feezen** [comment]
Bonsoir, merci de vos réponses.
J'ai refait le test en téléchargeant la dernière version, le problème persiste. J'ai bien mis '==' à la palce de '='.
Voici des screen d'un de mes test:
Le 1er event, dans lequel je met juste SV[1] à 10:
http://img11.hostingpics.net/pics/174598401.png
Le second event, la première page (qui est vide):
http://img11.hostingpics.net/pics/438607132.png
Et sa deuxième page avec le trigger:
http://img11.hostingpics.net/pics/872296923.png

Enfin, un gif du résultat:
http://img11.hostingpics.net/pics/200017test2.gif
On remarque bien que quand je met la valeur du SV[1] du 1er event à 10, le trigger du second est enclenché.

Dites moi si j'ai mal fait quelque chose, mais en faisant les mêmes test sous l'EE4 cela fonctionne :/

**Comment by Feezen** [comment]
Et même problème avec les SS sur des trigger :v

**Comment by Ibiky** [comment]
Pour le SS c'est tout à fait normal, le SS c'est un interrupteur local comme ceux de RM classique donc logique, il est possible que le problème vienne du Trigger le soucis, ont va tenté de voir ci cela vient de çà

**Comment by Feezen** [comment]
Je sais, justement, j'active le SS depuis un autre event (en faisant SS[1] = true) et ça s'active active le trigger d'un deuxième event.
Plus étrange encore, ça change aussi le trigger d'un event qui vérifie la valeur d'un SV en le désactivant :v

**Comment by Feezen** [comment]
Salut, je ne sais pas si le problème est résolu, mais pour vous montrer mes test j'upload une map (id5) sur laquelle j'ai fait des petits tests pour que vous puissiez voir par vous même.
Le lien (6ko):

https://www.dropbox.com/s/a36cufxuxpxhs18/Map005.rvdata2?dl=0

**Comment by Kadead** [comment]
J'ai exactement le meme probleme :-( des solutions?

**Comment by Ibiky** [comment]
Pas pour le moment, Nuki cherche d'où cela peut venir, dès qu'il trouve vous en serrai le plus vite informer du correctifs mis en place, encore désolé de ce désagrément, je me doute que vos projets sont en pose pour le moment à cause de ça et nous en somme navrer, donc patience merci, c'est en cours de correctif.

**Comment by xvw** [comment]
Je pense que le problème est fixé :) 
Merci pour votre aide :)

**Comment by Kadead** [comment]
Super! :D
Merci beaucoup! Vous êtes top :v

**Comment by Feezen** [comment]
Merci pour tout, ça marche parfaitement maintenant \o/
