### ISSUE TITLE
Create_****_area sa bug

### ISSUE THREAD

**Issue by Ibiky** [funkywork/RME#78]
Bonjour-soir.

Voila j'ai testé les commandes `area`. Par exemple j'ai utilisé la comande suivante : 
`create_rect_area(8, 6, 4, 7)` ou même `create_circle_area(8, 6, 3)`

J'ai directement une erreur script qui apparait, là voila : 

![Image du bug:](http://image.noelshack.com/fichiers/2015/14/1428183339-erreur-area.png)

ça me fait de même avec toutes les autres commandes area, a la place de Rect on aura l'erreur de l'area sera par exemple, Cercle ou même Ellipse ... Voila j'ai fais mon rapport merci a vous de vos futurs réponses.

Cordialement Ibiky.

**Comment by xvw** [comment]
Un petit fail de portée. Merci.
