### ISSUE TITLE
create_polygon_area bug

### ISSUE THREAD

**Issue by Ibiky** [funkywork/RME#81]
Bonjoirs, je reviens avec un souci sur la commande cette foi polygon, sur l’EE elle fonctionne très bien, mais sur RME j’ai un petit bug chelou, je fais ceci : 

![Image de l'event:](http://image.noelshack.com/fichiers/2015/15/1428782694-event-createpolygon.png) 

Suite à cela j’ai un bug sauvage qui apparait :

![Image du bug:](http://image.noelshack.com/fichiers/2015/15/1428782650-erreur-createpolygon.png)

Voilà je ne comprends pas pourquoi cela me fait ça, j’espère que vous trouverez le pourquoi du comment, ceci dis, merci de vos future réponse et/ou réparation.

Cordialement Ibiky.

**Comment by Jauke** [comment]
C'est corrigé, merci à toi.

En effet, dans l'EE4 on renseigne les points sous la forme "[[x,y], [x,y], etc.]", et j'ai vu que quelqu'un a changé le code pour RME de sorte à renseigner directement "[x,y], [x,y], [x,y]", mais il a rajouté une étoile en trop pour que ça fonctionne.

On peut encore décider de renseigner sous la forme "[[a,b], etc.]" ou "[a,b], etc." mais personnellement j'ai préféré remettre sous la forme "[[a,b], etc.]" comme dans l'EE4 pour poser moins de problèmes si on veut lister les points dans une variable à part comme dans ton exemple.

**Comment by Ibiky** [comment]
ah ok, cool, merci pour la résolution du probléme je vais pouvoir faire ma comande sur RME vue quelle fonctionne sur l'EE4.
